### ISSUE TITLE
frzr-deploy needs to generate initrd image on install and every update

### ISSUE THREAD

**Issue by alkazar** [gamer-os/frzr#1]
The OS image should provide an initrd image to be used. However, I was unable to get a pre-built initrd image to boot on actual hardware.

**Comment by sharkwouter** [comment]
I'm running into a related issue. To be able to add a module to the initrd, it needs to be already installed on the system which runs the mkinitcpio command. This makes it hard to add plymouth to already existing systems.

**Comment by alkazar** [comment]
fixed in frzr 0.4.0
