### ISSUE TITLE
allow splitting /home to a seperate drive when installing

### ISSUE THREAD

**Issue by eyecreate** [gamer-os/frzr#11]
Currently, when installing you select a single drive to install to. I'm interested in putting my /home as a partition on a different drive(taking up whole drive is fine) instead of a subvolume. This might be fringe enough to not support, but it doesn't seem like it should be too difficult. /home doesn't need to be upgraded so it doesn't need to be touched after install.

**Comment by sharkwouter** [comment]
Thanks for the report. I don't think I understand what you mean, though. Do you mean having multiple installation directories set at the same time?

**Comment by eyecreate** [comment]
Right now, this is how the installer sets things up:

    Drive1                              
    +------------------------------------+
    |   BTRFS /                          |
    |  +------------------------------+  |
    |  | /home          /etc          |  |
    |  | +------------++-------+      |  |
    |  | |            ||       |      |  |
    |  | |            ||       |      |  |
    |  | |            ||       |      |  |
    |  | |            ||       |      |  |
    |  | |            ||       |      |  |
    |  | |            ||       |      |  |
    |  | |            ||       |      |  |
    |  | +------------++-------+      |  |
    |  +------------------------------+  |
    |                                    |
    +------------------------------------+
This is how I want the installer to allow installing:

    Drive1                                    Drive2                              
    +------------------------------------+    +------------------------------------+
    |   BTRFS /                          |    |   ? /home                          |
    |  +------------------------------+  |    |  +------------------------------+  |
    |  |  /etc                        |  |    |  |                              |  |
    |  | +-------+                    |  |    |  |                              |  |
    |  | |       |                    |  |    |  |                              |  |
    |  | |       |                    |  |    |  |                              |  |
    |  | |       |                    |  |    |  |                              |  |
    |  | |       |                    |  |    |  |                              |  |
    |  | |       |                    |  |    |  |                              |  |
    |  | |       |                    |  |    |  |                              |  |
    |  | |       |                    |  |    |  |                              |  |
    |  | +-------+                    |  |    |  |                              |  |
    |  +------------------------------+  |    |  +------------------------------+  |
    |                                    |    |                                    |
    +------------------------------------+    +------------------------------------+

This allows having a smaller drive for the OS and larger one for storing games.

**Comment by sharkwouter** [comment]
Ah, now I get it. Not sure why I didn't understand in the first place. Thanks for clarifying.

I guess support for this could be done, but I'm not sure if it would provide us with a significant benefit. The root partition is so small that it doesn't really take away enough space to require a second disk. Even the smallest SSD would have a ton of free space left.

**Comment by eyecreate** [comment]
It is less important for saving space with the other partitions being small, but could still benefit from enabling slightly faster bootup using a ssd that won't store as many games as a larger mechanical drive.
As I said, it could be too niche a case, but is something I wanted to do to a machine I knew I could with other distro installers.

**Comment by eyecreate** [comment]
After thinking about it some more, It'd be more useful to consider RAID/LVM/etc before this. I'm closing this since this method seems of little benefit.
