### ISSUE TITLE
Lock FS

### ISSUE THREAD

**Issue by smumu** [gamer-os/frzr#12]
Hello,

I wanted to try some configuration changes so I ran `frzr-unlock`. Later, I reverted back my changes, and to be sure to not edit again I want to lock the system again.
As `fstab` is modified when unlocking, do I just need to revert the changes or should I change btrfs `ro` property too?

And for future usage, will a `frzr-lock` command be implemented or frzr is not intended to be locked after unlocking?

Thanks!

**Comment by alkazar** [comment]
I never really considered this. In general I dont think it is that useful, especially since we wont be able to undo any changes people could have made.

Everything will be reset upon next update.

**Comment by smumu** [comment]
I didn't know updating would revert back to readonly, thanks for this information.

So another question, more related to Gamer OS, is there a condition for an update to be downloaded? I'm on GamerOS 15 and I never received 16 nor 17 update. 
Maybe this can be related to my network, because when booting the computer says it is offline and I receive the "network connected" notification after 5 or 10 seconds. Do updates depends on network online target? If yes, should a `systemctl restart frzr-autoupdate.service` help to have update after network detected connection?

**Comment by alkazar** [comment]
The update service does already depend on the network being up. Are you sure the update service is failing?

You would also need to have the computer on long enough for the download to complete. One limitation is that it does not currently resume a download, but will start from scratch.

You can check on the status of the service with `journalctl -u frzr-autoupdate`.

You can also manually initiate a download by running `sudo frzr-deploy`. Just make sure the update service is not already downloading first.

**Comment by smumu** [comment]
frzr-autoupdate fails to start (and to restart). Launching frzr-deploy leads to an error:
```
tar: option ’--xattr’ is ambiguous; possibilities: ’--xattrs’ ’--xattrs-include’ ’--xattrs-include’
ERROR: empty stream is not considered valid
```

**Comment by smumu** [comment]
After searching, I found my `/frzr_root/channel` file contains `--help`, IDK how this is possible but I guess this is a wrong value?

**Comment by smumu** [comment]
I could update to GamerOS 17 by setting the content of `/frzr_root/channel` to `raw.githubusercontent.com/gamer-os/gamer-os/master/repos/default`, let me know if I should use another URL. Otherwise, this is issue an be closed.

Thanks for you help!
