### ISSUE TITLE
Make gameros check for new releases periodically via systemd timer

### ISSUE THREAD

**Issue by ChojinDSL** [gamer-os/frzr#15]
I use my gamer os machine as both a gaming device and a media player. As such, it's running 24/7 mostly. As far as I've understood correctly, Gameros only checks for new releases during boot. If it finds one, it will start downloading it and create a new subvolume to boot into on next boot.

For people who run their system 24/7 like me, this requires them to reboot at least twice to get a new release. Wouldn't it be simpler to have the frzr deploy service run at certain intervals in the background via  cron or systemd timer? E.g. check once every 24hours or so. Then the release would at least be ready for installation, requiring only one reboot.

**Comment by alkazar** [comment]
Yeah, this is a good idea.
