### ISSUE TITLE
Feature request: Add "add-ons" to an image managed by frzr

### ISSUE THREAD

**Issue by Samsagax** [gamer-os/frzr#18]
With the variety of systems and configurations that GamerOS is installed and run and with the variety of use cases for a couch gaming system (as a home server or media server for example) I think it makes sense to allow a base image to be deployed and a set of add-ons with bundles for each year case. Something like a mod system that fzrz could download and install.
That could make way for example to have a set of software for AMD GPUs, for NVIDIA GPUs , for media servers, for different kernels, etc.
Each add-on should be a set of packages and their configuration for the GamerOS system. They should be possible to select them at install-time and keep a record for frzr to download each of them in sequence. Then each time a new image is downloaded it also downloads each add-on for that image version.

**Comment by alkazar** [comment]
Not sure this is possible. How would it work?

**Comment by Samsagax** [comment]
> Not sure this is possible. How would it work?

I don't know how it could be possible as I don't know the internals of frzr but it could work like this:
- At install time the user would select from a list of add-ons. This add-ons should be a collection of packages (pacman packages) and configuration files for a set of desired functionality (this could be a set of amd tools, nvidia tools, some media servers, streaming services, etc.) this could make the base a little stripped of bloat, for example, I don't care about nvidia as I have a completely AMD setup, but the drivers should be part of the base, the tools can be separated.
- On the server side, those add-ons are packages downloadable by frzr and copied into the image. So we should make a base image and each add-on image with the same versio as the base.
- Then each time the system is updated, frzr should download the base image and each add-on selected by the user (that list should be kept from install time for example in a manifest file).
- Optionally the user could add an add-on for his current installation in the manifest file and in the next update (or by forcing an update) frzr could download those add-ons. The same for removal.

There should be a limited number of packages and addons. They should be only be targeted to specific use-cases of the GamerOS system. This woould also have the advantage of separating the development of those add-ons without breaking the base system designed specifically for couch gaming based on Steam.

**Comment by alkazar** [comment]
I don't really see the benefit and it seems like quite a maintenance hassle.

If someone wants to make and maintain an alternative image, they can do so pretty easily by forking the `gamer-os` repo.

What are the use cases that you would want as separate packs? I don't really see a reason to separate AMD and Nvidia for example.

**Comment by Samsagax** [comment]
I can see some use cases. But maybe you are right about the stage the project is at is not necessary as it would add a lot of maintenance nuances and annoyances. Feel free to close this issue
