### ISSUE TITLE
Failure to install to 8TB HDD

### ISSUE THREAD

**Issue by ShuffleBox** [gamer-os/frzr#7]
**Problem:** Installation fails when installing to a "large" hard drive that would require GPT partitioning.  
```
+ parted --script /dev/sda mklabel msdos mkpart primary fat32 1MiB 512MiB set 1 esp on mkpart primary 512MiB 100%
Error: partition length of 15627003904 sectors exceeds the msdos-partition-table-imposed maximum of 4294967295
```

**Cause:** frzr-bootstrap partitions the selected disk with a msdos label.  

**Hack resolution:**  Install nano (pacman -Sy nano) or vim. Edit /usr/bin/frzr-bootstrap line 44 & 55 (as applicable) from 'mklabel msdos' to 'mklabel gpt'.  Restart install.
Note: You can perform this edit from the start by accessing another terminal (eg. ctrl-alt-f2) and switching back to the original terminal, or after install fails, you can restart the install process by typing exit.

**Better resolution:** determine if drive requires gpt or msdos partition type and behave appropriately. 

https://github.com/gamer-os/frzr/blob/18361c65db2f7a4506d7884d5e1b66c482bd43c6/frzr-bootstrap#L44

https://github.com/gamer-os/frzr/blob/18361c65db2f7a4506d7884d5e1b66c482bd43c6/frzr-bootstrap#L55

**Comment by alkazar** [comment]
Nice find, thanks for the detailed report. I will switch to using GPT partition tables unconditionally.

**Comment by alkazar** [comment]
@ShuffleBox This should be fixed with the new ISO build: https://github.com/gamer-os/install-media/releases/download/2020-03-12/gameros-2020.03.12-x86_64.iso

If you have a chance to test it out, please report back. Thanks!

**Comment by ShuffleBox** [comment]
That looks to have done the trick on my system.  Thanks for fixing it up!
